/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Ejemplar;
import aplicacion.Usuario;

/**
 *
 * @author alumnogreibd
 */
public class VPrestamo extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    //Ejemplar ejemplarPrestar;
    Integer idLibro;
    Integer numEjemplar;
    /**
     * Creates new form VPrestamop
     */
    public VPrestamo(java.awt.Dialog parent, boolean modal, aplicacion.FachadaAplicacion fa, Integer idLibro, Integer numEjemplar) {
        super(parent, modal);
        
        this.fa = fa;
        this.idLibro = idLibro;
        this.numEjemplar = numEjemplar;
        
        initComponents();
        
        this.btnPrestarLibro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaId = new javax.swing.JTextField();
        etiquetaTitulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPrestarLibro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buscaNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscaId.setToolTipText("Titulo a buscar");
        buscaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaIdActionPerformed(evt);
            }
        });

        etiquetaTitulo.setText("Id:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPrestarLibro.setText("Prestar");
        btnPrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarLibroActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        tablaUsuarios.setModel(new ModeloTablaPrestamos());
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrestarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel4)
                    .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnPrestarLibro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaIdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarUsuarios();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        salirVentana();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarLibroActionPerformed
        // TODO add your handling code here:
        ModeloTablaPrestamos mp;
        mp = (ModeloTablaPrestamos) tablaUsuarios.getModel();
        
        Usuario usuario = null;
        
        if(mp.getRowCount() != 0)
        {
            usuario = mp.obtenerUsuario(tablaUsuarios.getSelectedRow());
            
            //Donde meter esta comprobacion?
            if(usuario.getPrestamosVencidos() == 0)
            {
                if(this.fa.prestarEjemplar(usuario.getIdUsuario(), idLibro, numEjemplar))
                {
                    salirVentana();
                }
            }
            else
            {
                this.fa.muestraExcepcion("O usuario ten prestamos vencidos!");
            }
        }
    }//GEN-LAST:event_btnPrestarLibroActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        actualizarEstadoBotons(tablaUsuarios.getSelectedRow());
    }//GEN-LAST:event_tablaUsuariosMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPrestarLibro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaId;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables

    public Integer getIdLibro()
    {
        return idLibro;
    }
    
    public Integer getNumEjemplar()
    {
        return numEjemplar;
    }
    
    public void buscarUsuarios(){
        ModeloTablaPrestamos m;

        m=(ModeloTablaPrestamos)tablaUsuarios.getModel();
        
        m.setFilas(fa.obtenerUsuariosPrestamos(buscaId.getText(), buscaNombre.getText()));
        if (m.getRowCount() > 0) {
            tablaUsuarios.setRowSelectionInterval(0, 0);
            
            actualizarEstadoBotons(0);
        }
    }
    
    public void salirVentana()
    {
        ((VLibro)super.getParent()).actualizarEjemplares();
        this.setVisible(false);
        this.dispose();
    }
    
    public void actualizarEstadoBotons(int i)
    {
        ModeloTablaPrestamos m = (ModeloTablaPrestamos)tablaUsuarios.getModel();
        
        if(m.getRowCount() > 0)
        {
            tablaUsuarios.setRowSelectionInterval(i,i);
            
            if(m.obtenerUsuario(i).getPrestamosVencidos() > 0)
            {
                btnPrestarLibro.setEnabled(false);
            }
            else
            {
                btnPrestarLibro.setEnabled(true);
            }
        }
        else
        {
            btnPrestarLibro.setEnabled(false);
        }
    }
}
